-- Drop tables if they exist
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;

-- Create Orders Table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  customer_name TEXT NOT NULL,
  school_name TEXT NOT NULL,
  directorate TEXT NOT NULL,
  governorate TEXT NOT NULL,
  district TEXT NOT NULL,
  phone TEXT NOT NULL,
  delivery_type INTEGER NOT NULL, -- 0: 'pickup', 1: 'delivery'
  delivery_cost NUMERIC DEFAULT 0,
  total_amount NUMERIC NOT NULL,
  status INTEGER DEFAULT 0 NOT NULL, -- 0: 'pending', 1: 'processing', 2: 'delivered', 3: 'cancelled'
  delivery_person TEXT,
  colleague_notes TEXT
);

-- Create Order Items Table
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  teacher_name TEXT NOT NULL,
  subject TEXT NOT NULL,
  grade TEXT NOT NULL,
  service_type INTEGER NOT NULL, -- 0: 'plan' (خطة فصلية), 1: 'prep' (تحضير يومي)
  price NUMERIC NOT NULL,
  quantity INTEGER DEFAULT 1
);

-- Enable Row Level Security
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Create policies (For this simple use case, we allow inserts from the storefront and full access from the dashboard)
-- Note: In a production app, you would want more restrictive policies based on authentication.

-- Allow anonymous inserts for orders
CREATE POLICY "Allow anonymous inserts" ON orders FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anonymous inserts" ON order_items FOR INSERT TO anon WITH CHECK (true);

-- Allow public read access to orders (for dashboard without auth for now)
CREATE POLICY "Allow public read" ON orders FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON order_items FOR SELECT TO public USING (true);

-- Allow public updates to orders (for dashboard without auth for now)
CREATE POLICY "Allow public updates" ON orders FOR UPDATE TO public USING (true);

-- Turn on Realtime for orders table
alter publication supabase_realtime add table orders;
alter publication supabase_realtime add table order_items;
