-- Drop tables if they exist
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS subjects;

-- Create Subjects Table
CREATE TABLE subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  plan_price NUMERIC NOT NULL,
  prep_price NUMERIC NOT NULL
);

-- Insert Default Subjects (Without ID, it will auto increment)
INSERT INTO subjects (name, plan_price, prep_price) VALUES
('التربية الإسلامية', 2, 2.5),
('اللغة العربية', 2, 2.5),
('اللغة الإنجليزية', 2, 2.5),
('الرياضيات', 2, 2.5),
('العلوم', 2, 2.5),
('الاجتماعيات', 2, 2.5),
('الفيزياء', 2, 2.5),
('الكيمياء', 2, 2.5),
('العلوم الحياتية', 2, 2.5),
('علوم الأرض', 2, 2.5),
('التاريخ', 2, 2.5),
('الجغرافيا', 2, 2.5),
('التربية الوطنية', 2, 2.5),
('الحاسوب', 2, 2.5),
('الثقافة المالية', 2, 2.5),
('تربية مهنية', 2, 2.5),
('علم النفس والاجتماع (ثاني عشر)', 2, 2.5),
('الفلسفة (ثاني عشر)', 2, 2.5);

-- Create Locations Table
CREATE TABLE locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  governorate TEXT NOT NULL UNIQUE,
  districts JSONB NOT NULL
);

-- Insert Default Locations
INSERT INTO locations (governorate, districts) VALUES
('عمان', '["إضافة", "قصبة عمان", "لواء الجامعة", "لواء القويسمة", "لواء ماركا", "لواء سحاب", "لواء الجيزة", "لواء الموقر", "لواء ناعور", "لواء وادي السير", "مرج الحمام", "تلاع العلي", "خلدا", "صويلح", "أبو نصير", "شفا بدران", "الجبيهة", "طبربور", "المقابلين", "اليادودة", "خريبة السوق", "عبدون", "الصويفية", "دير غبار", "الرابية", "الشميساني", "جبل عمان", "اللويبدة", "وسط البلد"]'),
('إربد', '["إضافة", "قصبة إربد", "بني عبيد", "المزار الشمالي", "الرمثا", "بني كنانة", "الأغوار الشمالية", "الكورة", "الطيبة", "الوسطية", "الحصن", "الصريح", "حوارة", "بشرى"]'),
('الزرقاء', '["إضافة", "قصبة الزرقاء", "الرصيفة", "الهاشمية", "الضليل", "الأزرق"]'),
('البلقاء', '["إضافة", "قصبة السلط", "الشونة الجنوبية", "دير علا", "عين الباشا", "الفحيص", "ماحص", "البقعة"]'),
('مادبا', '["إضافة", "قصبة مادبا", "ذيبان", "ماعين"]'),
('المفرق', '["إضافة", "قصبة المفرق", "البادية الشمالية", "البادية الشمالية الغربية", "الرويشد", "بلعما"]'),
('جرش', '["إضافة", "قصبة جرش", "المعراض", "برما"]'),
('عجلون', '["إضافة", "قصبة عجلون", "كفرنجة", "صخرة"]'),
('الكرك', '["إضافة", "قصبة الكرك", "القصر", "المزار الجنوبي", "الأغوار الجنوبية", "عي", "فقوع", "القطرانة", "مؤتة"]'),
('الطفيلة', '["إضافة", "قصبة الطفيلة", "بصيرا", "الحسا"]'),
('معان', '["إضافة", "قصبة معان", "البتراء (وادي موسى)", "الشوبك", "الحسينية"]'),
('العقبة', '["إضافة", "قصبة العقبة", "القويرة", "وادي عربة"]');

-- Create Orders Table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  customer_name TEXT NOT NULL,
  school_name TEXT NOT NULL,
  school_type TEXT, -- 'ذكور', 'إناث', 'مختلط'
  directorate TEXT NOT NULL,
  governorate TEXT NOT NULL,
  district TEXT NOT NULL,
  phone TEXT NOT NULL,
  phone2 TEXT,
  delivery_type INTEGER NOT NULL, -- 0: 'pickup', 1: 'delivery'
  school_location TEXT,
  home_location TEXT,
  delivery_cost NUMERIC DEFAULT 0,
  total_amount NUMERIC NOT NULL,
  status INTEGER DEFAULT 0 NOT NULL, -- 0: pending, 1: processing, 2: delivered, 3: cancelled, 4: rejected by teacher
  delivery_person TEXT,
  colleague_notes TEXT
);

-- Create Order Items Table
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  teacher_name TEXT NOT NULL,
  subject TEXT NOT NULL,
  grade TEXT NOT NULL,
  service_type INTEGER NOT NULL, -- 0: 'plan' (خطة فصلية), 1: 'prep' (تحضير يومي)
  price NUMERIC NOT NULL,
  quantity INTEGER DEFAULT 1
);

-- Create Notifications Table
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL, -- 'new', 'update'
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  is_read BOOLEAN DEFAULT FALSE
);

-- Enable Row Level Security
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Create policies (For this simple use case, we allow inserts from the storefront and full access from the dashboard)
-- Note: In a production app, you would want more restrictive policies based on authentication.

-- Allow anonymous inserts for orders
CREATE POLICY "Allow anonymous inserts" ON orders FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anonymous inserts" ON order_items FOR INSERT TO anon WITH CHECK (true);

-- Allow public read access to orders (for dashboard without auth for now)
CREATE POLICY "Allow public read" ON orders FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON order_items FOR SELECT TO public USING (true);

-- Allow public updates to orders (for dashboard without auth for now)
CREATE POLICY "Allow public updates" ON orders FOR UPDATE TO public USING (true);

-- Enable RLS and create policies for subjects table (for dashboard without auth)
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read subjects" ON subjects FOR SELECT TO public USING (true);
CREATE POLICY "Allow public insert subjects" ON subjects FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public update subjects" ON subjects FOR UPDATE TO public USING (true);
CREATE POLICY "Allow public delete subjects" ON subjects FOR DELETE TO public USING (true);

-- Enable RLS and create policies for locations table
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read locations" ON locations FOR SELECT TO public USING (true);
CREATE POLICY "Allow public insert locations" ON locations FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public update locations" ON locations FOR UPDATE TO public USING (true);
CREATE POLICY "Allow public delete locations" ON locations FOR DELETE TO public USING (true);

-- Enable RLS and create policies for notifications table
CREATE POLICY "Allow anonymous inserts notifications" ON notifications FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public read notifications" ON notifications FOR SELECT TO public USING (true);
CREATE POLICY "Allow public update notifications" ON notifications FOR UPDATE TO public USING (true);

-- Turn on Realtime for tables
alter publication supabase_realtime add table orders;
alter publication supabase_realtime add table order_items;
alter publication supabase_realtime add table notifications;
