-- =============================================================================
-- OPTIONAL RESET / WIPE DATABASE
-- Uncomment the DROP TABLE statements below ONLY if you want to completely 
-- wipe all existing tables and data to reset the database from scratch.
-- =============================================================================
-- DROP TABLE IF EXISTS notifications CASCADE;
-- DROP TABLE IF EXISTS order_items CASCADE;
-- DROP TABLE IF EXISTS orders CASCADE;
-- DROP TABLE IF EXISTS subject_grades CASCADE;
-- DROP TABLE IF EXISTS subjects CASCADE;
-- DROP TABLE IF EXISTS locations CASCADE;

-- =============================================================================
-- 1. TABLES CREATION (Safe & Idempotent)
-- =============================================================================

-- Create Subjects Table
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  plan_price NUMERIC NOT NULL,
  prep_price NUMERIC NOT NULL
);

-- Create subject_grades table
CREATE TABLE IF NOT EXISTS public.subject_grades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE,
  grade_name VARCHAR(50) NOT NULL,
  is_available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT unique_subject_grade UNIQUE (subject_id, grade_name)
);

-- Ensure is_available column exists on existing databases
ALTER TABLE public.subject_grades ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT TRUE;

-- Create Locations Table
CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  governorate TEXT NOT NULL UNIQUE,
  districts JSONB NOT NULL
);

-- Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  customer_name TEXT NOT NULL,
  school_name TEXT NOT NULL,
  school_type TEXT,
  directorate TEXT NOT NULL,
  governorate TEXT NOT NULL,
  district TEXT NOT NULL,
  phone TEXT NOT NULL,
  phone2 TEXT,
  delivery_type INTEGER NOT NULL,
  school_location TEXT,
  home_location TEXT,
  delivery_cost NUMERIC DEFAULT 0,
  total_amount NUMERIC NOT NULL,
  status INTEGER DEFAULT 0 NOT NULL,
  delivery_person TEXT,
  colleague_notes TEXT
);

-- Create Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  teacher_name TEXT NOT NULL,
  subject TEXT NOT NULL,
  grade TEXT NOT NULL,
  service_type INTEGER NOT NULL,
  price NUMERIC NOT NULL,
  quantity INTEGER DEFAULT 1
);

-- Create Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  is_read BOOLEAN DEFAULT FALSE
);

-- =============================================================================
-- 2. SEED DATA (Safe & Non-duplicating)
-- =============================================================================

-- Insert Default Subjects
INSERT INTO subjects (name, plan_price, prep_price)
SELECT name, plan_price, prep_price FROM (VALUES
  ('الاجتماعيات', 2, 2.5),
  ('التاريخ', 2, 2.5),
  ('التربية الإسلامية', 2, 2.5),
  ('التربية الوطنية', 2, 2.5),
  ('الثقافة المالية', 2, 2.5),
  ('الجغرافيا', 2, 2.5),
  ('الحاسوب', 2, 2.5),
  ('الرياضيات', 2, 2.5),
  ('العلوم', 2, 2.5),
  ('العلوم الحياتية', 2, 2.5),
  ('الفلسفة (ثاني عشر)', 2, 2.5),
  ('الفيزياء', 2, 2.5),
  ('الكيمياء', 2, 2.5),
  ('اللغة العربية', 2, 2.5),
  ('اللغة الإنجليزية', 2, 2.5),
  ('تربية مهنية', 2, 2.5),
  ('علم النفس والاجتماع (ثاني عشر)', 2, 2.5),
  ('علوم الأرض', 2, 2.5)
) AS v(name, plan_price, prep_price)
WHERE NOT EXISTS (SELECT 1 FROM subjects s WHERE s.name = v.name);

-- Insert Default Grades for All Subjects
INSERT INTO public.subject_grades (subject_id, grade_name, is_available)
SELECT s.id, g.grade_name, TRUE
FROM public.subjects s
CROSS JOIN (
  VALUES 
    ('الأول'),
    ('الثاني'),
    ('الثالث'),
    ('الرابع'),
    ('الخامس'),
    ('السادس'),
    ('السابع'),
    ('الثامن'),
    ('التاسع'),
    ('العاشر'),
    ('الحادي عشر (أكاديمي)'),
    ('الثاني عشر (أكاديمي)')
) AS g(grade_name)
ON CONFLICT (subject_id, grade_name) DO UPDATE SET is_available = EXCLUDED.is_available;

-- Insert Default Locations
INSERT INTO locations (governorate, districts) VALUES
('عمان', '["إضافة", "قصبة عمان", "لواء الجامعة", "لواء القويسمة", "لواء ماركا", "لواء سحاب", "لواء الجيزة", "لواء الموقر", "لواء ناعور", "لواء وادي السير", "مرج الحمام", "تلاع العلي", "خلدا", "صويلح", "أبو نصير", "شفا بدران", "الجبيهة", "طبربور", "المقابلين", "اليادودة", "خريبة السوق", "عبدون", "الصويفية", "دير غبار", "الرابية", "الشميساني", "جبل عمان", "اللويبدة", "وسط البلد"]'),
('إربد', '["إضافة", "قصبة إربد", "بني عبيد", "المزار الشمالي", "الرمثا", "بني كنانة", "الأغوار الشمالية", "الكورة", "الطيبة", "الوسطية", "الحصن", "الصريح", "حوارة", "بشرى"]'),
('الزرقاء', '["إضافة", "قصبة الزرقاء", "الرصيفة", "الهاشمية", "الضليل", "الأزرق"]'),
('البلقاء', '["إضافة", "قصبة السلط", "الشونة الجنوبية", "دير علا", "عين الباشا", "الفحيص", "ماحص", "البقعة"]'),
('مادبا', '["إضافة", "قصبة مادبا", "ذيبان", "ماعين"]'),
('المفرق', '["إضافة", "قصبة المفرق", "البادية الشمالية", "البادية الشمالية الغربية", "الرويشد", "بلعما"]'),
('جرش', '["إضافة", "قصبة جرش", "المعراض", "برما"]'),
('عجلون', '["إضافة", "قصبة عجلون", "كفرنجة", "صخرة"]'),
('الكرك', '["إضافة", "قصبة الكرك", "القصر", "المزار الجنوبي", "الأغوار الجنوبية", "عي", "فقوع", "القطرانة", "مؤتة"]'),
('الطفيلة', '["إضافة", "قصبة الطفيلة", "بصيرا", "الحسا"]'),
('معان', '["إضافة", "قصبة معان", "البتراء (وادي موسى)", "الشوبك", "الحسينية"]'),
('العقبة', '["إضافة", "قصبة العقبة", "القويرة", "وادي عربة"]')
ON CONFLICT (governorate) DO NOTHING;

-- =============================================================================
-- 3. SECURITY & POLICIES (Safe re-executable)
-- =============================================================================

-- Enable Row Level Security
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subject_grades ENABLE ROW LEVEL SECURITY;

-- Orders policies
DROP POLICY IF EXISTS "Allow anonymous inserts" ON orders;
CREATE POLICY "Allow anonymous inserts" ON orders FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read" ON orders;
CREATE POLICY "Allow public read" ON orders FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow public updates" ON orders;
CREATE POLICY "Allow public updates" ON orders FOR UPDATE TO public USING (true);

-- Order Items policies
DROP POLICY IF EXISTS "Allow anonymous inserts" ON order_items;
CREATE POLICY "Allow anonymous inserts" ON order_items FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read" ON order_items;
CREATE POLICY "Allow public read" ON order_items FOR SELECT TO public USING (true);

-- Subjects policies
DROP POLICY IF EXISTS "Allow public read subjects" ON subjects;
CREATE POLICY "Allow public read subjects" ON subjects FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow public insert subjects" ON subjects;
CREATE POLICY "Allow public insert subjects" ON subjects FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update subjects" ON subjects;
CREATE POLICY "Allow public update subjects" ON subjects FOR UPDATE TO public USING (true);

DROP POLICY IF EXISTS "Allow public delete subjects" ON subjects;
CREATE POLICY "Allow public delete subjects" ON subjects FOR DELETE TO public USING (true);

-- Locations policies
DROP POLICY IF EXISTS "Allow public read locations" ON locations;
CREATE POLICY "Allow public read locations" ON locations FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow public insert locations" ON locations;
CREATE POLICY "Allow public insert locations" ON locations FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update locations" ON locations;
CREATE POLICY "Allow public update locations" ON locations FOR UPDATE TO public USING (true);

DROP POLICY IF EXISTS "Allow public delete locations" ON locations;
CREATE POLICY "Allow public delete locations" ON locations FOR DELETE TO public USING (true);

-- Notifications policies
DROP POLICY IF EXISTS "Allow anonymous inserts notifications" ON notifications;
CREATE POLICY "Allow anonymous inserts notifications" ON notifications FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read notifications" ON notifications;
CREATE POLICY "Allow public read notifications" ON notifications FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow public update notifications" ON notifications;
CREATE POLICY "Allow public update notifications" ON notifications FOR UPDATE TO public USING (true);

-- Subject Grades policies
DROP POLICY IF EXISTS "Enable read access for all users" ON public.subject_grades;
CREATE POLICY "Enable read access for all users" ON public.subject_grades FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for all users" ON public.subject_grades;
CREATE POLICY "Enable insert for all users" ON public.subject_grades FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update for all users" ON public.subject_grades;
CREATE POLICY "Enable update for all users" ON public.subject_grades FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable delete for all users" ON public.subject_grades;
CREATE POLICY "Enable delete for all users" ON public.subject_grades FOR DELETE USING (true);

-- =============================================================================
-- 4. REALTIME PUBLICATION (Safe check)
-- =============================================================================
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE orders;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'order_items'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE order_items;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'notifications'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
  END IF;
END $$;
